name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Pdf
        run: |
          chmod +x ./latexdockercmd.sh
          ./latexdockercmd.sh /bin/sh -c "lualatex lwarp_template.tex"
          ./latexdockercmd.sh /bin/sh -c "lualatex lwarp_template.tex"
          ./latexdockercmd.sh /bin/sh -c "lwarpmk printindex"
          ./latexdockercmd.sh /bin/sh -c "lwarpmk print"
          ./latexdockercmd.sh /bin/sh -c "lwarpmk htmlindex || true"
          ./latexdockercmd.sh /bin/sh -c "lwarpmk html || true" 
          ./latexdockercmd.sh /bin/sh -c "bibtex lwarp_template_html"
          ./latexdockercmd.sh /bin/sh -c "lwarpmk html1 || true" 
          ./latexdockercmd.sh /bin/sh -c "lwarpmk limages || true"
          ./latexdockercmd.sh /bin/sh -c "lwarpmk htmlindex || true" 
          ./latexdockercmd.sh /bin/sh -c "bibtex lwarp_template_html"
          ./latexdockercmd.sh /bin/sh -c "lwarpmk html1 || true"
          ./latexdockercmd.sh /bin/sh -c "lwarpmk html || true" 
          mv lwarp_template.html index.html || true
          ls
          mv *.html output/ && mv *.css output/
          mkdir -p output/src
          ls *html
          mv *.html output/
          cp -R src/media output/src || true
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: output # The folder the action should deploy.
